version: '2'
services:
  zookeeper:
    image: ubuntu/zookeeper:edge
    ports:
      - 2181:2181
  
  kafka:
    image: ubuntu/kafka:3.1-22.04_beta
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      ZOOKEEPER_HOST: host.docker.internal
      ZOOKEEPER_PORT: 2181

  django_db:
    image: postgres:latest
    restart: always
    container_name: kafka-manager-db
    environment:
      POSTGRES_PASSWORD: local_development_only
      DJANGO_SECRET_KEY: abc

  djangoweb:
    image: kafka-manger:latest
    container_name: kafka-manager
    extra_hosts:
      - "apihost:127.0.0.1"
    environment:
      DATABASE_PASSWORD: local_development_only
      DATABASE_USER: postgres
      DATABASE_HOST: kafka-manager-db
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
      DJANGO_SECRET_KEY: awe123
      LOCAL_ADMIN_USER: admin
      LOCAL_ADMIN_PASS: admin
    command: >
      bash -c "sleep 2 && python3 manage.py migrate
      && echo \"from django.contrib.auth.models import User; import os; User.objects.filter(username=os.environ['LOCAL_ADMIN_USER']).exists() or User.objects.create_superuser(os.environ['LOCAL_ADMIN_USER'], '', os.environ['LOCAL_ADMIN_PASS'])\" | python3 manage.py shell
      && python3 manage.py runserver 0.0.0.0:8888"
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:8888:8888"
    depends_on:
      - django_db
      - kafka
