# Generated by Django 4.0.4 on 2022-05-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootstrap_servers', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KafkaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_partitions', models.PositiveIntegerField(default=2)),
                ('replication_factor', models.PositiveIntegerField(default=2)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka_manager_app.kafkacluster')),
            ],
        ),
        migrations.CreateModel(
            name='KafkaTopicACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('operation', models.IntegerField(choices=[(3, 'Read'), (4, 'Write'), (5, 'Create'), (6, 'Delete'), (7, 'Alter'), (8, 'Describe'), (10, 'Describe Configs'), (11, 'Alter Configs'), (12, 'Idempotent Write')])),
                ('permission', models.IntegerField(choices=[(2, 'Deny'), (3, 'Allow')])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka_manager_app.kafkatopic')),
            ],
        ),
        migrations.AddConstraint(
            model_name='kafkatopic',
            constraint=models.UniqueConstraint(fields=('name', 'cluster'), name='unique_name_per_cluster'),
        ),
    ]
