# Generated by Django 4.0.4 on 2022-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_manager_app', '0002_kafkacluster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafkatopic',
            name='description',
            field=models.JSONField(blank=True, null=dict),
            preserve_default=dict,
        ),
        migrations.AlterField(
            model_name='kafkacluster',
            name='description',
            field=models.JSONField(blank=True, null=dict),
        ),
    ]
