# Generated by Django 4.0.4 on 2022-05-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_manager_app', '0003_kafkatopic_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafkatopic',
            name='num_partitions',
        ),
        migrations.RemoveField(
            model_name='kafkatopic',
            name='replication_factor',
        ),
    ]
