# Generated by Django 4.0.4 on 2022-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_manager_app', '0004_remove_kafkatopic_num_partitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafkacluster',
            name='default_num_partitions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kafkacluster',
            name='default_replicaton_factor',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
