# Generated by Django 4.0.4 on 2022-04-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('bootstrap_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka_manager_app.kafkabootstrapsevers')),
            ],
        ),
    ]
