# Generated by Django 4.0.4 on 2022-04-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_manager_app', '0003_kafkatopics_unique_topic_per_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kafkatopics',
            old_name='bootstrap_server',
            new_name='bootstrap_servers',
        ),
    ]
