# Generated by Django 4.0.4 on 2022-04-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_manager_app', '0004_rename_bootstrap_server_kafkatopics_bootstrap_servers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kafkatopics',
            name='unique_topic_per_server',
        ),
        migrations.AddConstraint(
            model_name='kafkatopics',
            constraint=models.UniqueConstraint(fields=('topic', 'bootstrap_servers'), name='unique_topic_per_server'),
        ),
    ]
